# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 265)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_stop_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stop_2.setMinimumSize(QtCore.QSize(0, 100))
        self.Button_stop_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_stop_2.setFont(font)
        self.Button_stop_2.setObjectName("Button_stop_2")
        self.gridLayout.addWidget(self.Button_stop_2, 1, 1, 1, 1)
        self.Button_start_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start_1.setMinimumSize(QtCore.QSize(0, 100))
        self.Button_start_1.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_start_1.setFont(font)
        self.Button_start_1.setObjectName("Button_start_1")
        self.gridLayout.addWidget(self.Button_start_1, 0, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(0, 100))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 1, 2, 1, 1)
        self.Button_start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start_2.setMinimumSize(QtCore.QSize(0, 100))
        self.Button_start_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_start_2.setFont(font)
        self.Button_start_2.setObjectName("Button_start_2")
        self.gridLayout.addWidget(self.Button_start_2, 1, 0, 1, 1)
        self.lcdNumber_1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_1.setMinimumSize(QtCore.QSize(0, 100))
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.gridLayout.addWidget(self.lcdNumber_1, 0, 2, 1, 1)
        self.Button_stop_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stop_1.setMinimumSize(QtCore.QSize(0, 100))
        self.Button_stop_1.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_stop_1.setFont(font)
        self.Button_stop_1.setObjectName("Button_stop_1")
        self.gridLayout.addWidget(self.Button_stop_1, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_stop_2.setText(_translate("MainWindow", "stop 2"))
        self.Button_start_1.setText(_translate("MainWindow", "Start 1"))
        self.Button_start_2.setText(_translate("MainWindow", "Start 2"))
        self.Button_stop_1.setText(_translate("MainWindow", "stop 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
